version: '3'
services:
  postgres:
    image: postgres:12.1
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 54321:5432

  frontend:
    build: ./apps/frontend
    ports:
      - 5050:5000

volumes:
  db-data:
    driver: local
